GET http://localhost:3000/todos

###
GET http://localhost:3000/todos/632eb3df5584e5dd8291e880

###

POST http://localhost:3000/todos
Content-Type: application/json

{
    "task": "Get 8 hours of sleep"
}

###
DELETE http://localhost:3000/todos/632ee7d1dbdc4331d33d4776

###
PATCH http://localhost:3000/todos/632eb4cf4f53a26640e2b759
Content-Type: application/json

{
    "task": "Touch grass"
}